theme: 'minima'
plugins: [ 'jekyll-feed', 'jekyll-seo-tag' ]

minima: { date_format: "%b %-d, %Y" }
show_excerpts: false

domain: 'www.fixedpoints.net'
url: 'https://www.fixedpoints.net'
baseurl: ''

title: 'Fixed Points'
author: 'Jason Petersen'
email: 'webmaster@fixedpoints.net'
description: 'Things I keep returning to'

github_username: 'jasonmp85'
mastodon: [ { username: 'jason', instance: 'logoff.website' } ]

exclude:
  - '.jekyll-cache'
  - '.jekyll-metadata'
  - '.sass-cache'
  - 'CNAME'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'
  - 'vendor'
  - '_site'
