source 'https://rubygems.org'

# using GitHub pages rather than jekyll directly
gem 'github-pages', '~> 227'

# I'll still list it though, since we'll use it to test
gem 'jekyll', '~> 3.5'
gem 'faraday-retry', '~> 2.0'
gem 'webrick', '~> 1.7'

# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem 'minima', '~> 2.5'

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem 'jekyll-feed', '~> 0.9'
  gem 'jekyll-seo-tag', '~> 2.1'
end
